### ISSUE TITLE
$Config{perlpath} does not match $^X as expected for a relocatable perl

### ISSUE THREAD

**Issue by zmughal** [G4Vi/Perl-Dist-APPerl#6]
As per the recommendation for [`$^X`](https://perldoc.perl.org/5.36.0/variables/$%5EX), I have some code that uses `$Config{perlpath}`, however with `perl.com`, it gives the following:

```shell
$ /perl.com -MConfig -E 'for (my @perls = ($^X, $Config{perlpath}) ) { say "Trying $_"; system($_, qw{-E}, q{say "hello from ".shift @ARGV}, $_ ) == 0 or warn "failed $_: $!" }'
Trying /perl.com
hello from /perl.com
Trying /zip/bin/perl
failed /zip/bin/perl: ENOENT/2/No such file or directory at -e line 1.
```

A relocatable Perl would have them match as done [here](https://github.com/skaji/relocatable-perl/blob/5.36.0.1/build/relocatable-perl-build#L210).

**Comment by G4Vi** [comment]
Thanks for the report. It looks like `Config_heavy.pl` needs to be patched to set `perlpath`. The fix might be slightly more involved as the relocatable inc functions aren't added to `Config_heavy.pl` in non-relocatable inc builds.

**Comment by G4Vi** [comment]
Completed in 79a28e35551220091afab09d64833a33151bea2f, perlpath is set now to `$^X`.
https://github.com/G4Vi/Perl-Dist-APPerl/blob/79a28e35551220091afab09d64833a33151bea2f/share/5.36-cosmo3.patch#L302-L307
I was a little bit conflicted about adding it as it doesn't have the security benefits mentioned in the `$^X` documentation.

Additionally `$^X`/`$Config{perlpath}` should now be more reliable as now uses cosmo's `GetProgramExecutableName` instead of `argv[0]` so 

```c
#include <unistd.h>

int main(int argc, char *argv[]) {
    pid_t pid = fork();
    if (pid == 0 ) {
        char *newargv[] = {"hello", "-e", "print $^X", NULL};
        char *noenv[] = { NULL};
        execve("perl.com", newargv, noenv);
    } else {
        wait(NULL);
    }
}
```

prints `/path/to/perl.com` instead of `hello`.
